name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build the Docker image
      run: |
        docker buildx create --use
        docker buildx build --file Dockerfile --tag ghcr.io/${{ github.repository }}:latest --push .

    - name: Set image digest as an environment variable
      id: set_image_digest
      run: echo "::set-env name=IMAGE_DIGEST::$(docker inspect --format '{{index .RepoDigests 0}}' ghcr.io/${{ github.repository }}:latest)"

    - name: Save image digest to a file
      run: echo "${{ steps.set_image_digest.outputs.IMAGE_DIGEST }}" > image_digest.txt

    - name: Upload image digest as environment file
      uses: actions/upload-artifact@v2
      with:
        name: image-digest
        path: image_digest.txt
