name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build the Docker image
      run: |
        docker buildx create --use
        docker buildx build --file Dockerfile --tag ghcr.io/${{ github.repository }}:latest --push .

    - name: Set image digest as an environment variable
      id: set_image_digest
      run: echo "IMAGE_DIGEST=$(docker inspect --format '{{index .RepoDigests 0}}' ghcr.io/${{ github.repository }}:latest)" >> $GITHUB_ENV

    - name: Upload image digest as environment file
      uses: actions/upload-artifact@v2
      with:
        name: image-digest
        path: $GITHUB_ENV
