name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build the Docker image
      run: |
        docker buildx create --use
        docker buildx build --file Dockerfile --tag ghcr.io/${{ github.repository }}:latest --push .
